lane :bonjour do
  scan
end

lane :deploy do
  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "LAcrym0/fastlane-demo-moc2",
      name: version, #nom de la version sur GitHub
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: changelog_from_git_commits(),
      commitish: "master"
    )
  end
end